//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseContext.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingMenuItems = new HashSet<BookingMenuItem>();
            this.Payments = new HashSet<Payment>();
            this.TableBookings = new HashSet<TableBooking>();
        }
    
        public int Id { get; set; }
        public int Customer_id { get; set; }
        public int Restaurant_id { get; set; }
        public System.DateTime BookingMadeDate { get; set; }
        public System.TimeSpan BookingMadeTime { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public decimal PaymentTotal { get; set; }
        public Nullable<System.DateTime> PaymentMadeDate { get; set; }
        public int NoCustomers { get; set; }
        public string Comments { get; set; }
        public bool Cancelled { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingMenuItem> BookingMenuItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableBooking> TableBookings { get; set; }
    }
}
